# Generated by Django 2.0.1 on 2018-03-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scc_kanban', '0002_auto_20180321_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('outerspace', 'Launch It!'), ('headspace', 'In Headspace'), ('desk', 'On Desk'), ('monitor', 'Monitor'), ('board', 'On the Board'), ('icebox', 'In the Icebox'), ('bin', 'Throw it in the Bin')], max_length=32),
        ),
    ]
