# Generated by Django 2.0.1 on 2018-03-19 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BaseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('base_metric', models.ForeignKey(limit_choices_to={'record_type': 'base_record'}, on_delete=django.db.models.deletion.CASCADE, to='scc_kaizen.BaseMetric')),
            ],
        ),
        migrations.CreateModel(
            name='BooleanRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('base_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scc_kaizen.BaseRecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('base_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scc_kaizen.BaseRecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('record_type', models.CharField(choices=[('boolean', 'True/False'), ('integer', 'Count'), ('float', 'Value'), ('time', 'Time of Day'), ('duration', 'Duration of Time'), ('character', 'Short Description')], max_length=16)),
                ('base_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scc_kaizen.BaseMetric')),
            ],
        ),
        migrations.CreateModel(
            name='DurationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DurationField()),
                ('base_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scc_kaizen.BaseRecord')),
                ('detail_metric', models.ForeignKey(limit_choices_to={'record_type': 'duration'}, on_delete=django.db.models.deletion.CASCADE, to='scc_kaizen.DetailMetric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloatRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('base_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scc_kaizen.BaseRecord')),
                ('detail_metric', models.ForeignKey(limit_choices_to={'record_type': 'float'}, on_delete=django.db.models.deletion.CASCADE, to='scc_kaizen.DetailMetric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('base_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scc_kaizen.BaseRecord')),
                ('detail_metric', models.ForeignKey(limit_choices_to={'record_type': 'integer'}, on_delete=django.db.models.deletion.CASCADE, to='scc_kaizen.DetailMetric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TimeField()),
                ('base_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scc_kaizen.BaseRecord')),
                ('detail_metric', models.ForeignKey(limit_choices_to={'record_type': 'time'}, on_delete=django.db.models.deletion.CASCADE, to='scc_kaizen.DetailMetric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='characterrecord',
            name='detail_metric',
            field=models.ForeignKey(limit_choices_to={'record_type': 'character'}, on_delete=django.db.models.deletion.CASCADE, to='scc_kaizen.DetailMetric'),
        ),
        migrations.AddField(
            model_name='booleanrecord',
            name='detail_metric',
            field=models.ForeignKey(limit_choices_to={'record_type': 'boolean'}, on_delete=django.db.models.deletion.CASCADE, to='scc_kaizen.DetailMetric'),
        ),
    ]
