# Generated by Django 2.0.1 on 2018-03-19 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scc_kaizen', '0002_basemetric_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scc_kaizen.BaseRecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='detailmetric',
            name='record_type',
            field=models.CharField(choices=[('boolean', 'True/False'), ('integer', 'Count'), ('float', 'Value'), ('time', 'Time of Day'), ('duration', 'Duration of Time'), ('character', 'Short Description')], max_length=16),
        ),
        migrations.AddField(
            model_name='timerecord',
            name='detail_metric',
            field=models.ForeignKey(limit_choices_to={'record_type': 'time'}, on_delete=django.db.models.deletion.CASCADE, to='scc_kaizen.DetailMetric'),
        ),
    ]
