# Generated by Django 2.0.1 on 2018-03-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scc_kaizen', '0003_auto_20180318_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='value',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
